In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

from src.data.loader import *

## Data Loader

In [2]:
users = load_user_features()

videos = load_video_features_basic()

video_stats = load_video_features_statistics()

train = load_train_logs()

test = load_test_logs()

random = load_random_logs()

In [3]:
datasets = {
    "users": users,
    "videos": videos,
    "video_stats": video_stats,
    "train": train,
    "test": test,
    "random": random,
}

for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print(df.shape)
    display(df.head())

======================================================================
users
(27285, 31)

,user_id,user_active_degree,is_lowactive_period,is_live_streamer,is_video_author,follow_user_num,follow_user_num_range,fans_user_num,fans_user_num_range,friend_user_num,...,onehot_feat8,onehot_feat9,onehot_feat10,onehot_feat11,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17
0,0,full_active,0,1,1,514,500+,150,"[100,1k)",34,...,135,6,3,0,0.0,1.0,0.0,0.0,0.0,0.0
1,1,full_active,0,-124,1,457,"(250,500]",20,"[10,100)",3,...,283,6,2,2,1.0,0.0,1.0,0.0,0.0,0.0
2,2,full_active,0,-124,1,8,"(0,10]",26,"[10,100)",3,...,275,5,2,2,0.0,0.0,0.0,1.0,0.0,0.0
3,3,full_active,0,1,1,91,"(50,100]",2166,"[1k,5k)",14,...,118,6,2,2,1.0,0.0,0.0,0.0,0.0,0.0
4,4,full_active,0,-124,1,261,"(250,500]",10,"[10,100)",4,...,378,3,3,0,0.0,0.0,0.0,0.0,0.0,0.0

======================================================================
videos
(7583, 12)

,video_id,author_id,video_type,upload_dt,upload_type,visible_status,video_duration,server_width,server_height,music_id,music_type,tag
0,0,7349781,NORMAL,2022-04-10,LongImport,0.0,87433.0,720.0,1280.0,9155697141,9.0,39
1,1,2103883,NORMAL,2022-04-10,Kmovie,0.0,218066.0,720.0,1280.0,6355810746,9.0,2
2,2,5067285,NORMAL,2022-04-09,ShortImport,0.0,9233.0,720.0,1280.0,6618412736,4.0,1
3,3,7048760,NORMAL,2022-04-11,Web,0.0,16433.0,720.0,1280.0,9161677205,9.0,7
4,4,8635271,NORMAL,2022-04-09,Web,0.0,38766.0,720.0,1280.0,9141092381,9.0,9

======================================================================
video_stats
(7583, 52)

,video_id,counts,show_cnt,show_user_num,play_cnt,play_user_num,play_duration,complete_play_cnt,complete_play_user_num,valid_play_cnt,...,reduce_similar_user_num,collect_cnt,collect_user_num,cancel_collect_cnt,cancel_collect_user_num,direct_comment_user_num,reply_comment_user_num,share_all_cnt,share_all_user_num,outsite_share_all_cnt
0,0,102,2579.686275,2308.323529,816.882353,713.176471,2.767915e+07,195.254902,183.098039,443.019608,...,0.911765,0.901961,0.882353,0.235294,0.235294,0.156863,0.039216,0.117647,0.107843,0.078431
1,1,136,4027.992647,3368.367647,2116.250000,1864.044118,8.592152e+07,130.507353,125.941176,717.676471,...,2.279412,6.683824,6.470588,1.279412,1.176471,1.867647,0.551471,5.470588,4.963235,4.691176
2,2,91,666.703297,547.219780,425.681319,386.538462,4.197048e+06,80.208791,75.461538,95.725275,...,2.670330,1.835165,1.791209,0.681319,0.659341,1.153846,0.054945,0.296703,0.274725,0.285714
3,3,72,1134.194444,1097.958333,940.027778,854.833333,5.222510e+06,115.930556,92.194444,253.708333,...,0.805556,0.972222,0.875000,0.222222,0.180556,0.041667,0.000000,0.027778,0.027778,0.013889
4,4,178,4873.713483,4649.955056,4304.314607,3961.449438,1.119292e+08,1329.078652,1314.398876,2871.129213,...,3.971910,13.691011,13.410112,4.983146,4.825843,24.865169,15.286517,27.949438,25.775281,8.488764

======================================================================
train
(1141112, 19)

,user_id,video_id,date,hourmin,time_ms,is_click,is_like,is_follow,is_comment,is_forward,is_hate,long_view,play_time_ms,duration_ms,profile_stay_time,comment_stay_time,is_profile_enter,is_rand,tab
0,0,1527,20220411,1900,1649675512388,0,0,0,0,0,0,0,1385,209900,0,0,0,0,1
1,0,7405,20220416,2000,1650111976017,0,0,0,0,0,0,0,0,65400,0,0,0,0,0
2,0,6026,20220420,1600,1650444367095,0,0,0,0,0,0,0,1405,170833,0,0,0,0,1
3,1,6354,20220411,1100,1649645295928,0,0,0,0,0,0,0,0,255160,0,0,0,0,8
4,1,3645,20220411,1100,1649648827559,0,0,0,0,0,0,0,1970,79733,0,0,0,0,1

======================================================================
test
(295497, 19)

,user_id,video_id,date,hourmin,time_ms,is_click,is_like,is_follow,is_comment,is_forward,is_hate,long_view,play_time_ms,duration_ms,profile_stay_time,comment_stay_time,is_profile_enter,is_rand,tab
0,0,7531,20220422,1600,1650615878629,0,0,0,0,0,0,0,0,134156,0,0,0,0,0
1,0,4214,20220425,1800,1650882384975,0,0,0,0,0,0,0,1033,168241,0,0,0,0,1
2,0,3978,20220429,2100,1651237368151,0,0,0,0,0,0,0,0,129833,0,0,0,0,0
3,0,160,20220430,900,1651280365845,0,0,0,0,0,0,0,1114,109680,0,0,0,0,1
4,0,6946,20220502,1100,1651461680240,0,0,0,0,0,0,0,1931,12366,0,0,0,0,1

======================================================================
random
(1186059, 19)

,user_id,video_id,date,hourmin,time_ms,is_click,is_like,is_follow,is_comment,is_forward,is_hate,long_view,play_time_ms,duration_ms,profile_stay_time,comment_stay_time,is_profile_enter,is_rand,tab
0,0,5543,20220430,1800,1651314030792,0,0,0,0,0,0,0,863,30066,0,0,0,1,1
1,0,1836,20220502,1200,1651466607423,0,0,0,0,0,0,0,1190,132433,0,0,0,1,1
2,0,721,20220502,1700,1651481542743,0,0,0,0,0,0,0,1528,25266,0,0,0,1,1
3,0,442,20220502,1800,1651488577163,0,0,0,0,0,0,0,1490,12000,0,0,0,1,1
4,0,62,20220503,800,1651535940163,0,0,0,0,0,0,0,1419,169500,0,0,0,1,1

In [4]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.columns.tolist())

users
['user_id', 'user_active_degree', 'is_lowactive_period', 'is_live_streamer', 'is_video_author', 'follow_user_num', 'follow_user_num_range', 'fans_user_num', 'fans_user_num_range', 'friend_user_num', 'friend_user_num_range', 'register_days', 'register_days_range', 'onehot_feat0', 'onehot_feat1', 'onehot_feat2', 'onehot_feat3', 'onehot_feat4', 'onehot_feat5', 'onehot_feat6', 'onehot_feat7', 'onehot_feat8', 'onehot_feat9', 'onehot_feat10', 'onehot_feat11', 'onehot_feat12', 'onehot_feat13', 'onehot_feat14', 'onehot_feat15', 'onehot_feat16', 'onehot_feat17']

videos
['video_id', 'author_id', 'video_type', 'upload_dt', 'upload_type', 'visible_status', 'video_duration', 'server_width', 'server_height', 'music_id', 'music_type', 'tag']

video_stats
['video_id', 'counts', 'show_cnt', 'show_user_num', 'play_cnt', 'play_user_num', 'play_duration', 'complete_play_cnt', 'complete_play_user_num', 'valid_play_cnt', 'valid_play_user_num', 'long_time_play_cnt', 'long_time_play_user_num', 'short_time_play_cnt', 'short_time_play_user_num', 'play_progress', 'comment_stay_duration', 'like_cnt', 'like_user_num', 'click_like_cnt', 'double_click_cnt', 'cancel_like_cnt', 'cancel_like_user_num', 'comment_cnt', 'comment_user_num', 'direct_comment_cnt', 'reply_comment_cnt', 'delete_comment_cnt', 'delete_comment_user_num', 'comment_like_cnt', 'comment_like_user_num', 'follow_cnt', 'follow_user_num', 'cancel_follow_cnt', 'cancel_follow_user_num', 'share_cnt', 'share_user_num', 'download_cnt', 'download_user_num', 'report_cnt', 'report_user_num', 'reduce_similar_cnt', 'reduce_similar_user_num', 'collect_cnt', 'collect_user_num', 'cancel_collect_cnt', 'cancel_collect_user_num', 'direct_comment_user_num', 'reply_comment_user_num', 'share_all_cnt', 'share_all_user_num', 'outsite_share_all_cnt']

train
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

test
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

random
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

## Data Explorer

In [5]:
from src.data.explorer import DataExplorer

In [6]:
for name, df in datasets.items():

    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    DataExplorer.dataset_shape(df)

    display(
        DataExplorer.dataset_summary(df)
    )

================================================================================
USERS
================================================================================
Rows    : 27,285
Columns : 31

                   Column Data Type  Missing Values  Missing %  Unique Values
0                 user_id     int64               0       0.00          27285
1      user_active_degree       str               0       0.00              9
2     is_lowactive_period     int64               0       0.00              1
3        is_live_streamer     int64               0       0.00              2
4         is_video_author     int64               0       0.00              2
5         follow_user_num     int64               0       0.00           2562
6   follow_user_num_range       str               0       0.00              8
7           fans_user_num     int64               0       0.00           2210
8     fans_user_num_range       str               0       0.00              9
9         friend_user_num     int64               0       0.00           1391
10  friend_user_num_range       str               0       0.00              7
11          register_days     int64               0       0.00           2813
12    register_days_range       str               0       0.00              8
13           onehot_feat0     int64               0       0.00              2
14           onehot_feat1     int64               0       0.00              7
15           onehot_feat2     int64               0       0.00             50
16           onehot_feat3     int64               0       0.00           1471
17           onehot_feat4   float64             874       3.20             15
18           onehot_feat5     int64               0       0.00             34
19           onehot_feat6     int64               0       0.00              3
20           onehot_feat7     int64               0       0.00            118
21           onehot_feat8     int64               0       0.00            454
22           onehot_feat9     int64               0       0.00              7
23          onehot_feat10     int64               0       0.00              5
24          onehot_feat11     int64               0       0.00              5
25          onehot_feat12   float64             714       2.62              2
26          onehot_feat13   float64             714       2.62              2
27          onehot_feat14   float64             714       2.62              2
28          onehot_feat15   float64             714       2.62              2
29          onehot_feat16   float64             714       2.62              2
30          onehot_feat17   float64             714       2.62              2

================================================================================
VIDEOS
================================================================================
Rows    : 7,583
Columns : 12

            Column Data Type  Missing Values  Missing %  Unique Values
0         video_id     int64               0       0.00           7583
1        author_id     int64               0       0.00           6510
2       video_type       str               0       0.00              3
3        upload_dt       str               0       0.00              3
4      upload_type       str               0       0.00             14
5   visible_status   float64               0       0.00              1
6   video_duration   float64             239       3.15           5756
7     server_width   float64               0       0.00            156
8    server_height   float64               0       0.00            120
9         music_id     int64               0       0.00           7202
10      music_type   float64             203       2.68              5
11             tag       str              96       1.27            110

================================================================================
VIDEO_STATS
================================================================================
Rows    : 7,583
Columns : 52

,Column,Data Type,Missing Values,Missing %,Unique Values
0,video_id,int64,0,0.0,7583
1,counts,int64,0,0.0,125
2,show_cnt,float64,0,0.0,7583
3,show_user_num,float64,0,0.0,7583
4,play_cnt,float64,0,0.0,7580
5,play_user_num,float64,0,0.0,7583
6,play_duration,float64,0,0.0,7583
7,complete_play_cnt,float64,0,0.0,7573
8,complete_play_user_num,float64,0,0.0,7572
9,valid_play_cnt,float64,0,0.0,7581
10,valid_play_user_num,float64,0,0.0,7578
11,long_time_play_cnt,float64,0,0.0,7582
12,long_time_play_user_num,float64,0,0.0,7578
13,short_time_play_cnt,float64,0,0.0,7582
14,short_time_play_user_num,float64,0,0.0,7581
15,play_progress,float64,0,0.0,7583
16,comment_stay_duration,float64,0,0.0,7583
17,like_cnt,float64,0,0.0,7525
18,like_user_num,float64,0,0.0,7545
19,click_like_cnt,float64,0,0.0,7488
20,double_click_cnt,float64,0,0.0,7477
21,cancel_like_cnt,float64,0,0.0,7136
22,cancel_like_user_num,float64,0,0.0,7107
23,comment_cnt,float64,0,0.0,6906
24,comment_user_num,float64,0,0.0,6834
25,direct_comment_cnt,float64,0,0.0,6772
26,reply_comment_cnt,float64,0,0.0,5526
27,delete_comment_cnt,float64,0,0.0,3635
28,delete_comment_user_num,float64,0,0.0,3448
29,comment_like_cnt,float64,0,0.0,6867
30,comment_like_user_num,float64,0,0.0,6592
31,follow_cnt,float64,0,0.0,7117
32,follow_user_num,float64,0,0.0,7076
33,cancel_follow_cnt,float64,0,0.0,5999
34,cancel_follow_user_num,float64,0,0.0,5968
35,share_cnt,float64,0,0.0,6064
36,share_user_num,float64,0,0.0,5983
37,download_cnt,float64,0,0.0,5346
38,download_user_num,float64,0,0.0,5314
39,report_cnt,float64,0,0.0,406
40,report_user_num,float64,0,0.0,364
41,reduce_similar_cnt,float64,0,0.0,6802
42,reduce_similar_user_num,float64,0,0.0,6761
43,collect_cnt,float64,0,0.0,7290
44,collect_user_num,float64,0,0.0,7274
45,cancel_collect_cnt,float64,0,0.0,6680
46,cancel_collect_user_num,float64,0,0.0,6599
47,direct_comment_user_num,float64,0,0.0,6771
48,reply_comment_user_num,float64,0,0.0,5192
49,share_all_cnt,float64,0,0.0,6650
50,share_all_user_num,float64,0,0.0,6557
51,outsite_share_all_cnt,float64,0,0.0,6270

================================================================================
TRAIN
================================================================================
Rows    : 1,141,112
Columns : 19

               Column Data Type  Missing Values  Missing %  Unique Values
0             user_id     int64               0        0.0          26210
1            video_id     int64               0        0.0           7538
2                date     int64               0        0.0             13
3             hourmin     int64               0        0.0             24
4             time_ms     int64               0        0.0        1052464
5            is_click     int64               0        0.0              2
6             is_like     int64               0        0.0              2
7           is_follow     int64               0        0.0              2
8          is_comment     int64               0        0.0              2
9          is_forward     int64               0        0.0              2
10            is_hate     int64               0        0.0              2
11          long_view     int64               0        0.0              2
12       play_time_ms     int64               0        0.0         142635
13        duration_ms     int64               0        0.0           5726
14  profile_stay_time     int64               0        0.0            121
15  comment_stay_time     int64               0        0.0          21968
16   is_profile_enter     int64               0        0.0              2
17            is_rand     int64               0        0.0              1
18                tab     int64               0        0.0             15

================================================================================
TEST
================================================================================
Rows    : 295,497
Columns : 19

               Column Data Type  Missing Values  Missing %  Unique Values
0             user_id     int64               0        0.0          25877
1            video_id     int64               0        0.0           6618
2                date     int64               0        0.0             17
3             hourmin     int64               0        0.0             24
4             time_ms     int64               0        0.0         286277
5            is_click     int64               0        0.0              2
6             is_like     int64               0        0.0              2
7           is_follow     int64               0        0.0              2
8          is_comment     int64               0        0.0              2
9          is_forward     int64               0        0.0              2
10            is_hate     int64               0        0.0              2
11          long_view     int64               0        0.0              2
12       play_time_ms     int64               0        0.0          72673
13        duration_ms     int64               0        0.0           5181
14  profile_stay_time     int64               0        0.0             25
15  comment_stay_time     int64               0        0.0           9262
16   is_profile_enter     int64               0        0.0              2
17            is_rand     int64               0        0.0              1
18                tab     int64               0        0.0             15

================================================================================
RANDOM
================================================================================
Rows    : 1,186,059
Columns : 19

               Column Data Type  Missing Values  Missing %  Unique Values
0             user_id     int64               0        0.0          27285
1            video_id     int64               0        0.0           7583
2                date     int64               0        0.0             17
3             hourmin     int64               0        0.0             24
4             time_ms     int64               0        0.0        1185334
5            is_click     int64               0        0.0              2
6             is_like     int64               0        0.0              2
7           is_follow     int64               0        0.0              2
8          is_comment     int64               0        0.0              2
9          is_forward     int64               0        0.0              2
10            is_hate     int64               0        0.0              2
11          long_view     int64               0        0.0              2
12       play_time_ms     int64               0        0.0          69298
13        duration_ms     int64               0        0.0           5757
14  profile_stay_time     int64               0        0.0             41
15  comment_stay_time     int64               0        0.0           7681
16   is_profile_enter     int64               0        0.0              2
17            is_rand     int64               0        0.0              1
18                tab     int64               0        0.0              4

## Validator

In [7]:
from src.data.validator import DataValidator

for name, df in datasets.items():

    print(name)

    print(
        "Duplicate Rows:",
        DataValidator.duplicate_rows(df)
    )

    print("-" * 50)

users
Duplicate Rows: 0
--------------------------------------------------
videos
Duplicate Rows: 0
--------------------------------------------------
video_stats
Duplicate Rows: 0
--------------------------------------------------
train
Duplicate Rows: 15609
--------------------------------------------------
test
Duplicate Rows: 6378
--------------------------------------------------
random
Duplicate Rows: 10
--------------------------------------------------

# Data Profiling

In [8]:
from src.data.profiler import DataProfiler

In [9]:
for name, df in datasets.items():

    print("="*80)
    print(name.upper())
    print("="*80)

    display(DataProfiler.overview(df))

================================================================================
USERS
================================================================================

    Rows  Columns  Duplicate Rows  Missing Cells  Memory (MB)
0  27285       31               0           5158        12.72

================================================================================
VIDEOS
================================================================================

   Rows  Columns  Duplicate Rows  Missing Cells  Memory (MB)
0  7583       12               0            538         2.06

================================================================================
VIDEO_STATS
================================================================================

   Rows  Columns  Duplicate Rows  Missing Cells  Memory (MB)
0  7583       52               0              0         3.01

================================================================================
TRAIN
================================================================================

      Rows  Columns  Duplicate Rows  Missing Cells  Memory (MB)
0  1141112       19           15609              0       165.41

================================================================================
TEST
================================================================================

     Rows  Columns  Duplicate Rows  Missing Cells  Memory (MB)
0  295497       19            6378              0        42.83

================================================================================
RANDOM
================================================================================

      Rows  Columns  Duplicate Rows  Missing Cells  Memory (MB)
0  1186059       19              10              0       171.93

In [10]:
for name, df in datasets.items():

    print(name)

    display(
        DataProfiler.missing_summary(df)
    )

users

               Missing  Missing %
onehot_feat4       874       3.20
onehot_feat12      714       2.62
onehot_feat13      714       2.62
onehot_feat14      714       2.62
onehot_feat15      714       2.62
onehot_feat16      714       2.62
onehot_feat17      714       2.62

videos

                Missing  Missing %
video_duration      239       3.15
music_type          203       2.68
tag                  96       1.27

video_stats

Empty DataFrame
Columns: [Missing, Missing %]
Index: []

train

Empty DataFrame
Columns: [Missing, Missing %]
Index: []

test

Empty DataFrame
Columns: [Missing, Missing %]
Index: []

random

Empty DataFrame
Columns: [Missing, Missing %]
Index: []

In [11]:
for name, df in datasets.items():

    print(name)

    display(
        DataProfiler.cardinality(df)
    )

users

                       Unique Values  Unique %
user_id                        27285    100.00
register_days                   2813     10.31
follow_user_num                 2562      9.39
fans_user_num                   2210      8.10
onehot_feat3                    1471      5.39
friend_user_num                 1391      5.10
onehot_feat8                     454      1.66
onehot_feat7                     118      0.43
onehot_feat2                      50      0.18
onehot_feat5                      34      0.12
onehot_feat4                      15      0.05
fans_user_num_range                9      0.03
user_active_degree                 9      0.03
register_days_range                8      0.03
follow_user_num_range              8      0.03
friend_user_num_range              7      0.03
onehot_feat1                       7      0.03
onehot_feat9                       7      0.03
onehot_feat10                      5      0.02
onehot_feat11                      5      0.02
onehot_feat6                       3      0.01
is_live_streamer                   2      0.01
is_video_author                    2      0.01
onehot_feat14                      2      0.01
onehot_feat0                       2      0.01
onehot_feat12                      2      0.01
onehot_feat13                      2      0.01
onehot_feat16                      2      0.01
onehot_feat15                      2      0.01
onehot_feat17                      2      0.01
is_lowactive_period                1      0.00

videos

                Unique Values  Unique %
video_id                 7583    100.00
music_id                 7202     94.98
author_id                6510     85.85
video_duration           5756     75.91
server_width              156      2.06
server_height             120      1.58
tag                       110      1.45
upload_type                14      0.18
music_type                  5      0.07
video_type                  3      0.04
upload_dt                   3      0.04
visible_status              1      0.01

video_stats

                          Unique Values  Unique %
video_id                           7583    100.00
show_cnt                           7583    100.00
show_user_num                      7583    100.00
play_user_num                      7583    100.00
comment_stay_duration              7583    100.00
play_duration                      7583    100.00
play_progress                      7583    100.00
long_time_play_cnt                 7582     99.99
short_time_play_cnt                7582     99.99
short_time_play_user_num           7581     99.97
valid_play_cnt                     7581     99.97
play_cnt                           7580     99.96
valid_play_user_num                7578     99.93
long_time_play_user_num            7578     99.93
complete_play_cnt                  7573     99.87
complete_play_user_num             7572     99.85
like_user_num                      7545     99.50
like_cnt                           7525     99.24
click_like_cnt                     7488     98.75
double_click_cnt                   7477     98.60
collect_cnt                        7290     96.14
collect_user_num                   7274     95.93
cancel_like_cnt                    7136     94.11
follow_cnt                         7117     93.85
cancel_like_user_num               7107     93.72
follow_user_num                    7076     93.31
comment_cnt                        6906     91.07
comment_like_cnt                   6867     90.56
comment_user_num                   6834     90.12
reduce_similar_cnt                 6802     89.70
direct_comment_cnt                 6772     89.31
direct_comment_user_num            6771     89.29
reduce_similar_user_num            6761     89.16
cancel_collect_cnt                 6680     88.09
share_all_cnt                      6650     87.70
cancel_collect_user_num            6599     87.02
comment_like_user_num              6592     86.93
share_all_user_num                 6557     86.47
outsite_share_all_cnt              6270     82.68
share_cnt                          6064     79.97
cancel_follow_cnt                  5999     79.11
share_user_num                     5983     78.90
cancel_follow_user_num             5968     78.70
reply_comment_cnt                  5526     72.87
download_cnt                       5346     70.50
download_user_num                  5314     70.08
reply_comment_user_num             5192     68.47
delete_comment_cnt                 3635     47.94
delete_comment_user_num            3448     45.47
report_cnt                          406      5.35
report_user_num                     364      4.80
counts                              125      1.65

train

                   Unique Values  Unique %
time_ms                  1052464     92.23
play_time_ms              142635     12.50
user_id                    26210      2.30
comment_stay_time          21968      1.93
video_id                    7538      0.66
duration_ms                 5726      0.50
profile_stay_time            121      0.01
hourmin                       24      0.00
tab                           15      0.00
date                          13      0.00
is_click                       2      0.00
is_hate                        2      0.00
is_forward                     2      0.00
is_comment                     2      0.00
is_follow                      2      0.00
is_like                        2      0.00
long_view                      2      0.00
is_profile_enter               2      0.00
is_rand                        1      0.00

test

                   Unique Values  Unique %
time_ms                   286277     96.88
play_time_ms               72673     24.59
user_id                    25877      8.76
comment_stay_time           9262      3.13
video_id                    6618      2.24
duration_ms                 5181      1.75
profile_stay_time             25      0.01
hourmin                       24      0.01
date                          17      0.01
tab                           15      0.01
is_click                       2      0.00
is_hate                        2      0.00
is_forward                     2      0.00
is_comment                     2      0.00
is_follow                      2      0.00
is_like                        2      0.00
long_view                      2      0.00
is_profile_enter               2      0.00
is_rand                        1      0.00

random

                   Unique Values  Unique %
time_ms                  1185334     99.94
play_time_ms               69298      5.84
user_id                    27285      2.30
comment_stay_time           7681      0.65
video_id                    7583      0.64
duration_ms                 5757      0.49
profile_stay_time             41      0.00
hourmin                       24      0.00
date                          17      0.00
tab                            4      0.00
is_click                       2      0.00
is_hate                        2      0.00
is_forward                     2      0.00
is_comment                     2      0.00
is_follow                      2      0.00
is_like                        2      0.00
long_view                      2      0.00
is_profile_enter               2      0.00
is_rand                        1      0.00

# Analysis

## Recommedation Audit

In [12]:
from src.analysis.audit import RecommendationAudit

In [13]:
RecommendationAudit.interaction_summary(train)

               Metric                Value
0  Total Interactions              1141112
1        Unique Users                26210
2       Unique Videos                 7538
3          Date Range  20220409 - 20220421
4          Click Rate                46.34
5           Like Rate                 1.87
6         Follow Rate                  0.1
7      Long View Rate                33.66

In [14]:
RecommendationAudit.user_activity(train)

       interactions
count  26210.000000
mean      43.537276
std       44.711028
min        1.000000
25%       13.000000
50%       31.000000
75%       59.000000
max      809.000000

In [15]:
RecommendationAudit.video_popularity(train)

       interactions
count   7538.000000
mean     151.381268
std      365.539152
min        1.000000
25%       16.000000
50%       44.000000
75%      136.000000
max     9110.000000

### Business Question

In [16]:
### Q1. Which users are the most active?
(
    train
    .groupby("user_id")
    .size()
    .sort_values(ascending=False)
    .head(20)
)

user_id
22287    809
4592     698
21695    578
13893    525
6234     524
8387     499
793      497
23327    473
1702     458
25050    456
26971    454
10494    452
3198     444
17244    430
4991     418
15227    408
16496    408
7633     407
18622    388
2618     379
dtype: int64

In [17]:
### Q2. Which videos are recommended the most?
(
    train
    .groupby("video_id")
    .size()
    .sort_values(ascending=False)
    .head(20)

)

video_id
6921    9110
2303    7914
3310    7359
1868    6406
7136    5793
3587    4319
4636    3936
6714    3789
3273    3771
7177    3726
4955    3701
4644    3631
3706    3538
4506    3535
1725    3504
5391    3502
2383    3456
6989    3449
6504    3293
6769    3247
dtype: int64

In [18]:
### Q3. Which days have the highest traffic?

(
    train
    .groupby("date")
    .size()
    .sort_values(ascending=False)
)

date
20220411    278835
20220410    227808
20220412    166076
20220413     94711
20220414     71252
20220416     60904
20220415     58892
20220409     52736
20220417     44023
20220418     24560
20220420     20851
20220419     20443
20220421     20021
dtype: int64

In [19]:
### Q4. Which hours are busiest?

train["hour"] = (
    train["hourmin"] // 100
)

(
    train
    .groupby("hour")
    .size()
    .sort_values(ascending=False)
)

hour
22    89105
21    85935
20    76517
23    69959
19    69574
18    66039
12    62586
13    62303
17    60868
16    55574
11    52024
14    51557
15    50658
10    47579
9     43760
0     40846
8     39374
7     32665
1     23389
6     19230
2     14528
3      9770
5      9518
4      7754
dtype: int64

In [20]:
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    print(df.columns.tolist())
    print()

================================================================================
USERS
================================================================================
['user_id', 'user_active_degree', 'is_lowactive_period', 'is_live_streamer', 'is_video_author', 'follow_user_num', 'follow_user_num_range', 'fans_user_num', 'fans_user_num_range', 'friend_user_num', 'friend_user_num_range', 'register_days', 'register_days_range', 'onehot_feat0', 'onehot_feat1', 'onehot_feat2', 'onehot_feat3', 'onehot_feat4', 'onehot_feat5', 'onehot_feat6', 'onehot_feat7', 'onehot_feat8', 'onehot_feat9', 'onehot_feat10', 'onehot_feat11', 'onehot_feat12', 'onehot_feat13', 'onehot_feat14', 'onehot_feat15', 'onehot_feat16', 'onehot_feat17']

================================================================================
VIDEOS
================================================================================
['video_id', 'author_id', 'video_type', 'upload_dt', 'upload_type', 'visible_status', 'video_duration', 'server_width', 'server_height', 'music_id', 'music_type', 'tag']

================================================================================
VIDEO_STATS
================================================================================
['video_id', 'counts', 'show_cnt', 'show_user_num', 'play_cnt', 'play_user_num', 'play_duration', 'complete_play_cnt', 'complete_play_user_num', 'valid_play_cnt', 'valid_play_user_num', 'long_time_play_cnt', 'long_time_play_user_num', 'short_time_play_cnt', 'short_time_play_user_num', 'play_progress', 'comment_stay_duration', 'like_cnt', 'like_user_num', 'click_like_cnt', 'double_click_cnt', 'cancel_like_cnt', 'cancel_like_user_num', 'comment_cnt', 'comment_user_num', 'direct_comment_cnt', 'reply_comment_cnt', 'delete_comment_cnt', 'delete_comment_user_num', 'comment_like_cnt', 'comment_like_user_num', 'follow_cnt', 'follow_user_num', 'cancel_follow_cnt', 'cancel_follow_user_num', 'share_cnt', 'share_user_num', 'download_cnt', 'download_user_num', 'report_cnt', 'report_user_num', 'reduce_similar_cnt', 'reduce_similar_user_num', 'collect_cnt', 'collect_user_num', 'cancel_collect_cnt', 'cancel_collect_user_num', 'direct_comment_user_num', 'reply_comment_user_num', 'share_all_cnt', 'share_all_user_num', 'outsite_share_all_cnt']

================================================================================
TRAIN
================================================================================
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab', 'hour']

================================================================================
TEST
================================================================================
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

================================================================================
RANDOM
================================================================================
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']